@baseUrl = http://localhost:30100

###
# @name adminLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "login": "admin@user.com",
    "password": "SystemAdmin123@Senha"
}

@tokenAdmin = {{ adminLogin.response.body.access_token }}

###
GET {{baseUrl}}/users
Authorization: Bearer {{tokenAdmin}}

### Create Admin
POST {{baseUrl}}/users/admin
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}

{
    "name": "Admin",
    "login": "admin2@user.com",
    "email": "admin2@user.com",
    "password": "SystemAdmin123@Senha",
    "companyId": "COMPANY_ID_AQUI"
}

### Update Admin
PATCH {{baseUrl}}/users/USER_ID_AQUI
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}

{
    "name": "Admin Atualizado",
    "email": "admin@user.com"
}

### Create FIELD_TEAM
POST {{baseUrl}}/users
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}

{
    "name": "Equipe de Campo",
    "login": "field@user.com",
    "email": "field@user.com",
    "password": "SystemAdmin123@Senha",
    "role": "FIELD_TEAM"
}

### Create C2C
POST {{baseUrl}}/users
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}

{
    "name": "Operador C2C",
    "login": "c2c@user.com",
    "email": "c2c@user.com",
    "password": "SystemAdmin123@Senha",
    "role": "C2C",
    "permissions": [
        {
            "action": "read",
            "resource": "User"
        },
        {
            "action": "update",
            "resource": "WorkOrder",
            "condition": {
                "id": "1"
            }
        }
    ]
}

###
# @name fieldTeamLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "login": "field@user.com",
    "password": "SystemAdmin123@Senha"
}

@tokenFieldTeam = {{ fieldTeamLogin.response.body.access_token }}

###
# @name c2cLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "login": "c2c@user.com",
    "password": "SystemAdmin123@Senha"
}

@tokenC2c = {{ c2cLogin.response.body.access_token }}

### Listar ordens de serviço
GET {{baseUrl}}/work-orders
Authorization: Bearer {{tokenAdmin}}

### Listar localizações
GET {{baseUrl}}/locations
Authorization: Bearer {{tokenFieldTeam}}

### Listar usuários
GET {{baseUrl}}/users
Authorization: Bearer {{tokenAdmin}}

###
GET {{baseUrl}}/
Authorization: Bearer {{tokenC2c}}
