@baseUrl = http://localhost:30100
@tokenAdmin = {{ adminLogin.response.body.access_token }}
@tokenFieldTeam = {{ fieldTeamLogin.response.body.access_token }}

###
# @name fieldTeamLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "login": "field.empresa@user.com",
    "password": "SystemAdmin123@Senha"
}

###
GET {{baseUrl}}/users
Authorization: Bearer {{tokenFieldTeam}}

###
GET {{baseUrl}}/users/USER_ID_AQUI
Authorization: Bearer {{tokenFieldTeam}}

###
# @name adminLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "login": "systemadmin@user.com",
    "password": "SystemAdmin123@Senha"
}

###
GET {{baseUrl}}/users
Authorization: Bearer {{tokenAdmin}}

###
GET {{baseUrl}}/users?companyId=COMPANY_ID_AQUI
Authorization: Bearer {{tokenAdmin}}

###
GET {{baseUrl}}/users/USER_ID_AQUI
Authorization: Bearer {{tokenAdmin}}

### Empresas (tenants)
GET {{baseUrl}}/companies
Authorization: Bearer {{tokenAdmin}}

### Regionais
GET {{baseUrl}}/regionals
Authorization: Bearer {{tokenAdmin}}

### Localizações
GET {{baseUrl}}/locations
Authorization: Bearer {{tokenAdmin}}

### Ativos
GET {{baseUrl}}/assets
Authorization: Bearer {{tokenAdmin}}

### Ordens de serviço
GET {{baseUrl}}/work-orders
Authorization: Bearer {{tokenAdmin}}

### Planejamentos
GET {{baseUrl}}/planning
Authorization: Bearer {{tokenAdmin}}

### Filas
GET {{baseUrl}}/queues
Authorization: Bearer {{tokenAdmin}}

### IP Locations
GET {{baseUrl}}/ip-locations
Authorization: Bearer {{tokenAdmin}}

### Notificações
GET {{baseUrl}}/notifications
Authorization: Bearer {{tokenAdmin}}

### Arquivos
GET {{baseUrl}}/files
Authorization: Bearer {{tokenAdmin}}

### Documentos
GET {{baseUrl}}/documents
Authorization: Bearer {{tokenAdmin}}

### Create System Admin
POST {{baseUrl}}/users/system-admin
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}

{
    "name": "System Admin",
    "login": "systemadmin@user.com",
    "email": "systemadmin@user.com",
    "password": "SystemAdmin123@Senha"
}

### Create Admin
POST {{baseUrl}}/users/admin
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}

{
    "name": "Admin",
    "login": "admin2@user.com",
    "email": "admin2@user.com",
    "password": "SystemAdmin123@Senha",
    "companyId": "COMPANY_ID_AQUI"
}

### Create FIELD_TEAM
POST {{baseUrl}}/users
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}

{
    "name": "Equipe de Campo",
    "login": "field@user.com",
    "email": "field@user.com",
    "password": "SystemAdmin123@Senha",
    "role": "FIELD_TEAM",
    "companyId": "COMPANY_ID_AQUI"
}

### Create C2C
POST {{baseUrl}}/users
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}

{
    "name": "Operador C2C",
    "login": "c2c@user.com",
    "email": "c2c@user.com",
    "password": "SystemAdmin123@Senha",
    "role": "C2C",
    "companyId": "COMPANY_ID_AQUI"
}
